# -*- coding: utf-8 -*-
"""get_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_UMmh-RB_f8CdfO94aSMUl9MTaAEi0eB
"""

import numpy as np
import os
import cv2

from google.colab import drive
drive.mount('/content/drive/')

cd drive/

path='/content/drive/My Drive/raw/'

name_list=os.listdir(path)

x=[]
y=[]
for i in range(len(name_list)):
  path2=os.path.join(path,name_list[i])
  for img in os.listdir(path2):
    im=cv2.imread(os.path.join(path2,img))
    im=cv2.resize(im,(224,224))
    x.append(im)
    y.append(i)

x=np.array(x)
y=np.array(y)

x.shape

y.shape

np.save('x_dat',x)

np.save('y_dat',y)